# Generated by Django 3.2.5 on 2021-07-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
